from liquidacion import calcular_liquidacion_definitiva
print("Bienvenido a la Calculadora de Liquidación Definitiva")
print("Por favor, ingrese los siguientes datos:")
salario = float(input("Salario mensual: "))
dias = int(input("Días trabajados: "))
print("Si no recibe auxilio de transporte, ingrese 0. De lo contrario, ingrese el valor del auxilio de transporte:")
auxilio = float(input("Auxilio de transporte: "))
resultado = calcular_liquidacion_definitiva(salario, dias, auxilio)
print("\nResultados de la liquidación definitiva:")
print(f"Cesantías: {resultado['cesantias']}")
print(f"Intereses sobre cesantías: {resultado['intereses_cesantias']}")
print(f"Prima: {resultado['prima']}")
print(f"Vacaciones: {resultado['vacaciones']}")
print(f"Total a pagar: {resultado['total']}")
